### ISSUE TITLE
Error Downloading Images

### ISSUE THREAD

**Issue by alanblue2000** [selbetar/askfmArchiver#5]
Successfully ran software, generated .md, downloaded all .gif and videos, HOWEVER, no images where downloaded.
______________________________________________________________________________________________________________________________________
CMD prompt for each failure:

DownloadMedia() Exception: URL is:
An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetByteArrayAsync(String requestUri)
   at askfmArchiver.Utils.NetworkManager.DownloadMedia(String url, String file) in C:\Users\ET\askfmArchiver\askfmArchiver\Utils\NetworkManager.cs:line 67
______________________________________________________________________________________________________________________________________
Further, .md message for each failure:

! [MISSING: Visuals Folder] (./output/visuals_XXXXXX\140532899439.)
______________________________________________________________________________________________________________________________________

There is, of course, a visuals folder as this is where the .gif and videos have been saved.
**Any ideas? Thank you in advance, help appreciated.**

**Comment by selbetar** [comment]
Thanks for reporting the bug. It happened because the underlying HTML of `ask.fm` changed. I have pushed a fix and published a new release. Unfortunately, there is no error recovery mechanism right now, so the only way to get the images uploaded by that specific user is to either drop the data of that user from the database, or to delete the database and start from scratch (not advisable if you have more than one user in the database).

However, there's a new version being developed that will be capable of error recovery, so if your database is big and has more than one user, I would suggest that you wait for the new release `(v3.0.0)`.
